### ISSUE TITLE
의견: Google Hack fair 에 나가보면 어떨까요?

### ISSUE THREAD

**Issue by dusskapark** [bobplanet/bobplanet.github.io#1]
[관련 포스팅](http://googledevkr.blogspot.kr/2015/10/hack.html)

구글의 기술을 많이 쓰는 것이 중요한데, 
이미 구글 클라우드로 진헌규 매니저님이 구현을 거의 다 하셨고 이렇게 저렇게 검토를 해보면 괜찮을 것 같습니다. 
일종의 _목표점_ 으로 괜찮을 것 같습니다. 

~~넥서스5갖고싶습니다~~

**Comment by hkjinlee** [comment]
뭐 까짓거 나갑시다. 관련 진행은 @dusskapark 님께서 챙겨주세요.

PS. issue 게시판이 두개가 생기니 좀 헷갈리는데, 일단 Bobplanet 프로젝트의 이슈게시판을 쓰십시다. 이쪽 이슈 게시판은 닫아둘께요.
